# serverless.yml

service: translate

provider:
  name: aws
  runtime: python3.6
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: "arn:aws:s3:::vgvcode.speakppt/*"
    - Effect: "Allow"
      Action:
        - "polly:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "elastictranscoder:Read*"
        - "elastictranscoder:List*"
        - "elastictranscoder:*Job"
        - "elastictranscoder:*Preset"
        - "s3:ListAllMyBuckets"
        - "s3:ListBucket"
        - "s3:ListObjects"
        - "iam:ListRoles"
        - "sns:ListTopics"
      Resource: "*"

functions:
  translate2ppt:
    handler: translate2ppt.lambda_handler
  translate2speech:
    handler: translate2speech.lambda_handler
  mp3towav:
    handler: mp3towav.lambda_handler

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
